# Generated by Django 5.1.1 on 2025-04-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgfinance', '0002_cardcollection'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardpricehistory',
            index=models.Index(fields=['card_name', 'date'], name='mtgfinance__card_na_d672b1_idx'),
        ),
    ]
